# Generated by Django 2.2.19 on 2021-05-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoacademicaapp', '0002_categoria_conta_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
