# Generated by Django 2.2.19 on 2021-06-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoacademicaapp', '0003_auto_20210526_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], max_length=11),
        ),
    ]
